# Generated by Django 4.2.3 on 2023-07-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbool', '0002_place_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='Booking',
        ),
        migrations.AlterModelTable(
            name='place',
            table='Place',
        ),
    ]
